runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.7
  
manual_scaling:
  instances: 1
  
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  
readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

#[START gae_flex_storage_yaml]
env_variables:
  CLOUD_STORAGE_BUCKET: eastern-crawler-311200.appspot.com
#[END gae_flex_storage_yaml]
